### ISSUE TITLE
Sir,Can you tell me how to compile the 51822`s Program of Transmitters?

### ISSUE THREAD

**Issue by latincompass** [mattdibi/redox-w-firmware#10]
If you need technical support, have some question or want new features added on the Redox Wireless please use the [official Redox repository](https://github.com/mattdibi/redox-keyboard/issues).

If you want to report a bug, discuss improvement or anything else regarding the NRF51822 firmware for the Redox wire less, you're in the right place!
Sir,Can you tell me how to compile the 51822`s Program of Transmitters?

**Comment by mattdibi** [comment]
Hi,

the complete instruction are available [here](https://github.com/mattdibi/redox-w-firmware#install-dependencies). Hope this helps.

**Comment by latincompass** [comment]
> Hi,
> 
> the complete instruction are available [here](https://github.com/mattdibi/redox-w-firmware#install-dependencies). Hope this helps.

Thanks a lot Sir,but i still want know which IDE used to Compile the 51822`s Program of Transmitters?can you help me.

**Comment by mattdibi** [comment]
There’s no IDE, the instructions I linked are used to install Nordicsemi SDK which is what is called by the scripts (‘program_left.sh’ and ‘program_right.sh’) to compile the Redox wireless firmware.

**Comment by latincompass** [comment]
> There’s no IDE, the instructions I linked are used to install Nordicsemi SDK which is what is called within the scripts (`program_left.sh` and `program_right.sh`) to compile the Redox wireless firmware.

THANKS a lot , I will try to it.
