### ISSUE TITLE
Troubleshooting guide

### ISSUE THREAD

**Issue by cvanelteren** [mattdibi/redox-w-firmware#2]
Hi,

First off, thanks for providing the schematics for your receiver, and the great looking board in general. I have had some issues with getting my board to work. Can you provide some insights in the problems I am facing.

I have correctly assembled the receiver provided by your schematics and double checked the continuity accross all components. However, no LEDs light up when plugging in my pro micro. There is a very faint green light when I press the reset button. When I do a diode check the LED lights up only if the pro micro is disconnected or when it connect it directly to ground. 

All the NRF chips are flashed with the firmware you provided. The promicro is flashed with the precompiled hex. 

Can you provide a description of what the LEDs should do under normal operation?
Do you have any idea what could be wrong with the setup?

Thanks in advance.

**Comment by mattdibi** [comment]
Hi,

>  However, no LEDs light up when plugging in my pro micro.

Not good. Power LEDs and serial comm should light up.

>  There is a very faint green light when I press the reset button. When I do a diode check the LED lights up only if the pro micro is disconnected or when it connect it directly to ground.

I would look for a short. Some pins somewhere are connected and they shouldn't.

**Comment by cvanelteren** [comment]
Thanks for the comment. I will have a look at it again this weekend. I have been quite busy last week. I have the suspicion that my clone micro controllers are the issue. I have a few pro micros here but two of them produce the behavior above.

**Comment by cvanelteren** [comment]
Few weeks later. I have tried to debug this issue and have now tested the issue on two separate pcbs. Checking for continuity I can't seem to find a short anywhere yet on both pcbs (both on the pro micro side as well as on the BLE chip). Diode checks work when the board is detached from the pro micro, but not when atttatched to the pro micro. Do you have any clues as to what the cause and or where the short could be?

I have included some pics when it is plugged in
![image](https://user-images.githubusercontent.com/19485143/57195639-4f9b6c80-6f55-11e9-8e62-d9c13d1cd523.png)

![image](https://user-images.githubusercontent.com/19485143/57195643-53c78a00-6f55-11e9-86cd-21f7ca8e8298.png)

**Comment by mattdibi** [comment]
Unfortunately I really can't tell anything from the pictures. Looks like they were compressed once uploaded. Could you send them to me using my [email](matthewdibi@gmail.com)? Also add a pic of the underside of the PCB if you can.

**Comment by kilaketia** [comment]
Hi, could you help me too ? I assembled your receiver and the pro micro power led is on but not the rx or tx led is on. I can flash the nrf chip successfully, I don't find any short. Do you have any idea please ?

**Comment by mattdibi** [comment]
Hi,
did you flash the pro micro with QMK? the rest of the keyboard is working?

**Comment by kilaketia** [comment]
Yes and probably, can't say without a receiver working. I messed with the pins of my yj-14015 on the receiver so now I have to wait for a new one.

**Comment by mattdibi** [comment]
I would say that this is the expected behaviour then. Update me when you'll get the new YJ-14015.

**Comment by kilaketia** [comment]
Hi, I finally received the new YJ-14015 and I soldered a new board. And after some code digging, I found out that I actually set the wrong pinout in the firmware for my keyboard (I made my own based on yours and other design). Now it's finally working.

Except one key. The diode is okay, the same key works on the other side and it doesn't show up with hid-recorder. The whole collum and row works except him. If you have any idea, please say so. I'm out of ideas.

**Comment by mattdibi** [comment]
Hi,

double check soldering. 

Also double check the key itself, even though it's a rare occurance, it can be a bad switch (happened to me once).

**Comment by kilaketia** [comment]
Hi, the pcb was faulty.

Thanks.
