### ISSUE TITLE
Estimate battery life with 4dBm transmit power

### ISSUE THREAD

**Issue by drfloob** [mattdibi/redox-w-firmware#9]
Tech support requested, if you've got the time! I'm having some signal issues with the redox-w, solved by placing the receiver ~1 foot from the boards. Like others, even with the falba bamboo case, I can't put anything in between the receiver and the transmitters, and I often experience repeated or missing key presses.

I'd like to test beefing up the gazelle tx signal strength to 4dBm but I'm curious if you could run the power measurements with the shunt resistor to estimate battery life as you did before. I believe the default transmit power is 0dBm ([docs](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk5.v15.0.0/group__gzll__02__api.html#ga8be12e26c93ee706e89b0ec2a491c6ab)). I'm still just getting my feet wet in electronics, else I'd take a stab at it myself.

**Comment by mattdibi** [comment]
Hi,

I'll see what I can do. I keep my Redox at work, I need to get there and take it home for testing so give me a couple of days. ;)

**Comment by mattdibi** [comment]
Hi,

I used the [nrf_gzll_set_tx_power](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v15.0.0%2Fgroup__gzll__02__api.html&anchor=ga8be12e26c93ee706e89b0ec2a491c6ab) function to set the power to 4dB.

Can't see any difference. Maybe my scope can't pick up the difference... Here's the pic with the same settings:
![20191007_220303](https://user-images.githubusercontent.com/22748355/66346006-8127c200-e951-11e9-889a-6d108a450b73.jpg)

I suggest you to give it a try.
